import {ALL_TALENTS} from './content.mjs';
import {rankSteps,rankData,currentRank} from './talent-ranks.mjs';
import {CANON119,CANON_SPLITS119} from './talent-canon119.mjs';

const NS='gahla-resurrected',descriptions=new Set(['Szkolenie Mnicha','Naturalna Obrona','Nadludzka Siła','Bestialska Hybryda']);
export const splitId=(id,index)=>index?String(id).slice(0,12).padEnd(12,'x')+String(index).padStart(4,'0'):id;
export function migrateItemData119(raw){
 if(raw.type==='talent'&&['Bestialska Hybryda','Zmiennokształtny'].includes(raw.name)&&!raw.flags?.[NS]?.formCanon119){
  const input=structuredClone(raw);input.flags??={};input.flags[NS]??={};delete input.flags[NS].talent119;input.flags[NS].formCanon119=true;
  if(raw.name==='Bestialska Hybryda'&&(Number(raw.system?.rank)>1||Number(raw.system?.level)>=4||Number(raw.system?.effectTier)>=4||Number(raw.flags?.[NS]?.legacy118?.level)>=4))input.flags[NS].legacyHybridRank119={system:structuredClone(raw.system),prior:structuredClone(raw.flags?.[NS]?.legacy118??null),reason:'Historyczna płatna ranga Hybrydy wymaga kontroli MG; EXP i historia bez zmian.'};
  return migrateItemData119(input);
 }
 const data=structuredClone(raw);if(data.type!=='talent')return [data];if(data.flags?.[NS]?.talent119){if(data.name==='Nasycenie Źródła Mocy'&&data.system?.description?.includes('Każdy Tier źródła +5 testu rzucania i 1 opcja umagicznienia.'))data.system.description=data.system.description.replace('Każdy Tier źródła +5 testu rzucania i 1 opcja umagicznienia.','Gotowe Źródło daje bazowo stałe +5 do testów rzucania, niezależnie od Tieru. Każdy Tier Źródła daje 1 wybór umagicznienia (łącznie tyle wyborów, ile wynosi Tier Źródła).').replace('Test ½ UM albo WIA + ½ ER + 5×Tier talentu.','Test tworzenia/ulepszania: ½ głównej statystyki (UM albo WIA) + ½ ER + 5×Tier talentu Nasycenie Źródła Mocy.');return [data];}
 const names=CANON_SPLITS119[data.name]??[data.name];return names.map((name,index)=>{const out=structuredClone(data),def=ALL_TALENTS.find(t=>t.name===name);if(!CANON119[name]||!def)return out;const oldEffect=Number(data.system.effectTier||data.system.level||1),steps=rankSteps(def),rank=Math.max(1,steps.filter(s=>s.effectTier<=oldEffect).length);out.name=name;if(data._id)out._id=splitId(data._id,index);out.system={...out.system,...rankData(def,rank),requirements:def.requirements,description:def.description};out.flags??={};out.flags[NS]??={};out.flags[NS].legacy119={rank:data.system.rank,level:data.system.level,effectTier:data.system.effectTier,requiredTier:data.system.requiredTier,costLevel:data.system.costLevel,name:data.name,description:data.system.description};out.flags[NS].talent119=true;if(names.length>1)out.flags[NS].splitOrigin119=data._id;if(oldEffect<steps[0].effectTier){out.system.level=oldEffect;out.system.effectTier=oldEffect;out.flags[NS].legacyEffectPending119=true;}if(name==='Uzdolnienie Artystyczne')out.flags[NS].artChoice??=null;return out;});
}
export function migrateLedger119(ledger){const result=structuredClone(ledger);if(result.canon119){for(const entry of result.entries??[])for(const change of entry.undo?.items??[])for(const key of ['before','after'])if(change[key])change[key]=migrateItemData119(change[key])[0];return result;}for(const entry of result.entries??[]){const changes=[];for(const change of entry.undo?.items??[]){
 const after=migrateItemData119({_id:change.id,...change.after}),before=change.before?migrateItemData119({_id:change.id,...change.before}):[];
 after.forEach((a,index)=>{const b=before[index]??null;delete a._id;if(b)delete b._id;changes.push({id:splitId(change.id,index),before:b,after:a});});
 if(change.after?.type==='talent'){const def=ALL_TALENTS.find(d=>d.name===after[0].name);if(def){entry.rank=currentRank(after[0],def);entry.costLevel??=Number(change.after.system.level);entry.requiredTier=after[0].system.requiredTier;if(change.before&&change.after.system.level!==change.before.system.level&&after[0].system.effectTier===before[0]?.system.effectTier)entry.emptyLegacyPurchase=true;}}
 }if(entry.undo)entry.undo.items=changes;}result.canon119=true;return result;}
function snapshot(item){const raw=item.toObject?.()??item;return structuredClone({_id:item.id??raw._id,name:raw.name,type:raw.type,system:raw.system,flags:raw.flags??{}});}
async function migrateCollection(parent){for(const item of Array.from(parent.items??[])){
 const source=snapshot(item),parts=migrateItemData119(source);for(const extra of parts.slice(1)){const existing=Array.from(parent.items).find(i=>i.id===extra._id);if(existing&&existing.flags?.[NS]?.splitOrigin119!==source._id)throw Error('Kolizja ID migracji talentu '+extra.name);if(!existing)await parent.createEmbeddedDocuments('Item',[{...(item.toObject?.()??{}),...extra}],{keepId:true,gahlaMigration119:true});}
 if(JSON.stringify(source)!==JSON.stringify(parts[0])){const {_id,...patch}=parts[0];await item.update(patch,{gahlaMigration119:true});}
 }
 const temporary=parent.flags?.[NS]?.automation?.temporary??[],removed=temporary.filter(e=>e.name==='Bestialska Hybryda'||e.id==='hybrid4');
 if(removed.length){const automation=structuredClone(parent.flags[NS].automation);automation.temporary=temporary.filter(e=>!removed.includes(e));await parent.update({['flags.'+NS+'.automation']:automation,['flags.'+NS+'.legacyHybridT4Review119']:{removed:structuredClone(removed),resources:structuredClone(automation.resources??{})}});}
 if(parent.flags?.[NS]?.development&&(!parent.flags?.[NS]?.ledger119||JSON.stringify(parent.flags[NS].development)!==JSON.stringify(migrateLedger119(parent.flags[NS].development))))await parent.update({['flags.'+NS+'.development']:migrateLedger119(parent.flags[NS].development),['flags.'+NS+'.ledger119']:true});
}
export async function migrate119(){if(!game.user.isGM||Array.from(game.users??[]).filter(u=>u.isGM&&u.active).sort((a,b)=>a.id.localeCompare(b.id))[0]?.id!==game.user.id)return;
 const actors=new Map(Array.from(game.actors??[]).map(a=>[a.uuid,a]));for(const scene of game.scenes??[])for(const t of scene.tokens??[])if(t.actor&&!t.actorLink)actors.set(t.actor.uuid,t.actor);for(const actor of actors.values())await migrateCollection(actor);
 const migrateWorld=async(collection,create)=>{for(const item of Array.from(collection)){const source=snapshot(item),parts=migrateItemData119(source);for(const extra of parts.slice(1)){const existing=Array.from(collection).find(i=>i.id===extra._id);if(existing&&existing.flags?.[NS]?.splitOrigin119!==source._id)throw Error('Kolizja ID migracji '+extra.name);if(!existing)await create({...item.toObject?.(),...extra});}if(JSON.stringify(source)!==JSON.stringify(parts[0])){const {_id,...patch}=parts[0];await item.update(patch,{gahlaMigration119:true});}}};
 await migrateWorld(game.items??[],data=>Item.create(data,{keepId:true,gahlaMigration119:true}));
 for(const pack of game.packs??[]){if(!['Item','Actor'].includes(pack.documentName)||!['world','gahla-resurrected'].includes(pack.metadata?.packageName))continue;const locked=pack.locked;try{const docs=await pack.getDocuments();if(locked)await pack.configure({locked:false});if(pack.documentName==='Actor')for(const actor of docs)await migrateCollection(actor);else await migrateWorld(docs,data=>Item.create(data,{pack:pack.collection,keepId:true,gahlaMigration119:true}));}finally{if(locked)await pack.configure({locked:true});}}
}
export function register119(){Hooks.on('preCreateItem',(item,_data,options)=>{if(options?.gahlaMigration119)return;const parts=migrateItemData119(snapshot(item));if(parts.length===1){const {_id,...patch}=parts[0];item.updateSource(patch);}else ui.notifications.warn('Stary Mistrz Ukrywania / Cichy Ruch zostanie rozdzielony przy ponownym uruchomieniu świata przez MG.');});}
