import {requireOwner,serial} from './automation-runtime.mjs';
import {WEAPON_PROFILES} from './weapon-profiles.mjs';
export {WEAPON_PROFILES} from './weapon-profiles.mjs';
export function monkTalent(actor){return Array.from(actor.items??[]).find(i=>i.type==='talent'&&i.system.learned&&i.name==='Szkolenie Mnicha');}
export function monkAttack(actor,weapon){const item=monkTalent(actor);if(!item)return {bgl:0,dice:0};const id=weapon?.system?.profileId;
 const unarmed=id==='unarmed';const matching=Boolean(id&&WEAPON_PROFILES[id]&&id===item.system.monkWeaponType&&!weapon.system.isRanged&&!weapon.system.reload);
 return {bgl:unarmed||matching?(Number(item.system.level)>=2?30:20):0,dice:unarmed?1:0};
}
export function monkView(actor){const t=monkTalent(actor),selected=t?.system.monkWeaponType;return {has:Boolean(t),missing:Boolean(t&&!selected),name:WEAPON_PROFILES[selected]??'Nie wybrano',canChoose:Boolean(t&&(game.user.isGM||actor.isOwner&&!selected))};}
export async function chooseMonkWeapon(actor,type){requireOwner(actor);if(!WEAPON_PROFILES[type])throw Error('Wybierz legalny rodzaj broni wręcz.');return serial(actor.uuid,async()=>{const item=monkTalent(actor);if(!item)throw Error('Brak Szkolenia Mnicha.');if(item.system.monkWeaponType&&!game.user.isGM)throw Error('Wybraną Broń Mnicha może zmienić tylko MG.');const previous=item.system.monkWeaponType;await item.update({'system.monkWeaponType':type});try{const ledger=actor.flags?.['gahla-resurrected']?.development;if(ledger){const next=structuredClone(ledger);for(const entry of next.entries??[])for(const change of entry.undo?.items??[])if(change.id===item.id)for(const key of ['before','after'])if(change[key])change[key].system.monkWeaponType=type;await actor.setFlag('gahla-resurrected','development',next);}}catch(error){await item.update({'system.monkWeaponType':previous},{gahlaMigration118:true});throw error;}return true;});}
export async function promptMonkWeapon(){const esc=foundry.utils.escapeHTML;const result=await foundry.applications.api.DialogV2.input({window:{title:'Szkolenie Mnicha'},content:'<p>Wybierz broń, w której Twoja postać szkoliła się przez całe życie.</p><select name="weaponType">'+Object.entries(WEAPON_PROFILES).map(([id,label])=>'<option value="'+id+'">'+esc(label)+'</option>').join('')+'</select><p>Walka bez broni jest zawsze częścią szkolenia. Późniejszej korekty wyboru dokonuje MG.</p>',ok:{label:'Zatwierdź'}});if(!result)return null;if(!WEAPON_PROFILES[result.weaponType])throw Error('Niepoprawna Broń Mnicha.');return result.weaponType;}
