/** Rank is an actual purchase; level remains the legacy effect-tier compatibility field. */
export const SPLIT_TALENTS={
 'Mocne Płuca / Pływak / Wspinacz':[
  ['Mocne Płuca','Oddech trwa dwa razy dłużej.'],['Pływak','T1: Ułatwienie pływania. T3: pełna SZ w wodzie.'],['Wspinacz','T1: Ułatwienie wspinaczki. T3: tańsza wspinaczka; dokładną zniżkę ustala MG — źródło nie podaje liczby.']],
 'Kartograf / Sztuka Rysunku / Poliglota':[
  ['Kartograf','T1: Ułatwienie do ER/PER przy tworzeniu i odczytywaniu map. T3: możesz tworzyć fałszywe mapy i ukryte oznaczenia; odpowiedni test z Ułatwieniem.'],['Sztuka Rysunku','T1: Ułatwienie do ZR/ER przy tworzeniu realistycznych rysunków, portretów i precyzyjnych planów. T3: bardzo wiarygodne fałszerstwa dokumentów; odpowiedni test ZR/ER z Ułatwieniem.'],['Poliglota','T1: znasz 1 dodatkowy język. T3: w interakcjach z użytkownikami tego języka masz Ułatwienie do odpowiednich testów Ogłady.']],
 'Sztuka Kulinarna / Zielarstwo':[['Sztuka Kulinarna','T1: Ułatwienie przygotowania posiłków. T3: posiłek daje +1 tymczasowej ŻYW.'],['Zielarstwo','T1: Ułatwienie zielarstwa. T3: mikstura leczy 1 Ranę.']]
};
SPLIT_TALENTS['Opanowanie Instrumentu / Uzdolnienie Artystyczne / Znawca Bestii']=[['Opanowanie Instrumentu','T1: Ułatwienie do OG podczas gry na instrumencie. T3: raz na walkę, za 3 segmenty muzyka daje Ułatwienie do następnego testu sojusznika.'],['Uzdolnienie Artystyczne','T1: Ułatwienie występów artystycznych. Przypisanie efektu T3 z dawnego wspólnego opisu wymaga decyzji projektowej.'],['Znawca Bestii','T1: Ułatwienie do OG przy oswajaniu i opanowaniu dzikich zwierząt. T3: raz na sesję darmowa akcja uspokojenia dzikiej bestii, test OG z Ułatwieniem.']];
SPLIT_TALENTS['Doświadczony Wojak / Doświadczenie Strzelca']=[['Doświadczony Wojak','T1: 1 przerzut trafienia w zwarciu na walkę. T3: łącznie 2 przerzuty.'],['Doświadczenie Strzelca','T1: 1 przerzut trafienia z dystansu na walkę. T3: łącznie 2 przerzuty.']];
const two13=['Opanowanie Instrumentu','Uzdolnienie Artystyczne','Znawca Bestii','Doświadczony Wojak','Doświadczenie Strzelca','Mocne Kości','Wnikliwość','Większa Muskulatura','Gibkość','Uczony','Większa Ogłada','Potencjał Magiczny','Potencjał Duchowy','Pływak','Wspinacz','Kartograf','Sztuka Rysunku','Poliglota','Sztuka Kulinarna','Zielarstwo','Cztery Ręce','Niezmordowany','Strateg','Znawca Rynku','Mocne Płuca / Pływak / Wspinacz','Kartograf / Sztuka Rysunku / Poliglota','Sztuka Kulinarna / Zielarstwo','Opanowanie Instrumentu / Uzdolnienie Artystyczne / Znawca Bestii'];
export const RANK_TIERS=Object.fromEntries(two13.map(n=>[n,[1,3]]));
Object.assign(RANK_TIERS,{'Odporność na Klimat':[1,2],'Naturalna Ochrona Trucizny':[1,4],'Medycyna Zaawansowana':[1,3],'Nienaturalnie Odporny':[1,3,4],'Łamacz Zbroi':[2,3,4],'Kontrolowana Sekwencja':[3,4],'Wielostrzał':[3,4],'Mistrz Tarczy':[1,2,3,4],'Mistrz Parowania':[1,2,3,4],'Mistrz Bloku':[1,2,3,4]});
for(const name of ['Mocne Płuca','Mocny Cios','Precyzyjny Strzał','Śmiertelny Cios','Blokada Aury','Szybki Refleks','Szybka Wymiana','Przycelowanie','Sokole Oko','Akrobatyczny Unik','Wojak','Żelazne Natarcie','Mistrz Run','Niosący Sprawiedliwość','Święty Płomień','Wola Życia','Dotyk Litości','Płomyk Nadziei','Głos Otuchy','Niezłomna Wiara','Spojrzenie Herolda','Serce Burzy','Gniew Burzy','Pewny Krok','Rytuał Dwoistości','Purpurowa Maska','Kielich Rozpusty','Taniec Satyra','Ziarna Czasu','Pętla Przeznaczenia','Spojrzenie w Przyszłość','Głos Wyroczni','Nić Przeznaczenia','Honor Wojownika','Jedność z Naturą','Szept Puszczy','Rytualna Ofiara','Krwawe Przymierze','Sługa Martwego Oblicza','Szept zza Grobu','Krok w Cieniu','Nosiciel Niegodziwości','Spaczenie Materii'])RANK_TIERS[name]=[1];
RANK_TIERS['Mistrz Run']=[3];RANK_TIERS['Sokole Oko']=[3];
RANK_TIERS['Doświadczenie Magiczne / Kapłańskie']=[1,3];RANK_TIERS['Doświadczony Wojak / Doświadczenie Strzelca']=[1,3];RANK_TIERS['Bestialska Hybryda']=[1];
export const TRUE_FOUR=new Set(['Wytrzymały','Krwisty Metabolizm','Krasnoludzkie Rzemiosło','Plotkowanie','Pierwsza Pomoc','Jeździectwo','Wiedza Wybrana','Dyplomata','Oburęczny','Żywotny','Odporny Fizycznie','Odporny Psychicznie','Odporny Magicznie','Odporny Duchowo','Celny Cios','Szybki','Umiejętności Magiczne','Biegłość Magiczna','Pamięć Maga','Modlitwa','Ulubione zaklęcie / cud','Mistrzostwo Aury','Magiczne Powidoki','Energia Krwi','Święte Dłonie','Specjalny Manewr','Mistrz Broni','Szkolenie Oręża','Szybkie Przeładowanie','Szybka Regeneracja','Naturalna Obrona','Runotwórstwo','Chwyt Tytana','Przeczucie Przyszłości']);
export function rankSteps(def){const tiers=def.rankTiers??RANK_TIERS[def.name]??Array.from({length:def.maxRank??def.maxLevel??4},(_,i)=>i+1);return tiers.map((effectTier,i)=>({rank:i+1,effectTier,requiredTier:Math.max(effectTier,...[...String(def.requirements??'').matchAll(/(?:\bTier\s*|\bT\s*)([1-4])\b/gi)].map(m=>Number(m[1]))),costLevel:effectTier}));}
export function rankStep(def,rank){return rankSteps(def)[Number(rank)-1]??null;}
export function currentRank(item,def={name:item?.name,maxLevel:item?.system?.maxLevel}){if(!item)return 0;return Number(item.system?.rank)>0?Number(item.system.rank):Math.max(1,rankSteps(def).filter(r=>r.effectTier<=Number(item.system?.level||1)).length);}
export function effectTier(item){return Number(item?.system?.effectTier)||Number(item?.system?.level)||0;}
export function rankCost(def,rank,teacher=false){const step=rankStep(def,rank);return step?Math.floor(Number(def.costBase??50)*step.costLevel*(teacher?0.5:1)):Infinity;}
export function rankData(def,rank){const s=rankStep(def,rank);if(!s)throw Error('Nie istnieje taka ranga talentu.');return {...s,level:s.effectTier,maxRank:rankSteps(def).length,maxLevel:Math.max(...rankSteps(def).map(s=>s.effectTier))};}
