import {NS} from './effects-engine.mjs';
import {tier119} from './talent-values119.mjs';
import {auraAccess} from './canonical-rules.mjs';
import {serial,requireOwner} from './automation-runtime.mjs';
export const reservedAura119=actor=>Object.values(actor?.flags?.[NS]?.auraReservations119??{}).reduce((n,v)=>n+Math.max(0,Number(v)||0),0);
export function auraPayment119(system){try{return Number(JSON.parse(system?.builderState||'{}').pay_aura||0);}catch{return 0;}}
export function validateAuraPayment119(actor,amount,itemId){const tier=tier119(actor,'Duchowa Pięść'),max=tier>=4?3:tier>=3?2:0;if(!Number.isInteger(amount)||amount<0||amount>max)throw Error('Skupienie Bojowe: limit '+max+' punktów Aury na Manewr.');const old=Number(actor?.flags?.[NS]?.auraReservations119?.[itemId]||0);if(amount&&(!auraAccess(actor).allowed||Number(actor.system.combat.aura.value)+old<amount))throw Error('Brak dostępnej Aury do zablokowania w Manewrze.');return old;}
export async function saveAuraManeuver119(actor,item,data){requireOwner(actor);return serial(actor.uuid,async()=>{const id=item?.id??foundry.utils.randomID(),amount=auraPayment119(data.system),old=validateAuraPayment119(actor,amount,id),before=structuredClone(actor.flags?.[NS]?.auraReservations119??{}),after={...before,[id]:amount},aura=Number(actor.system.combat.aura.value);if(!amount)delete after[id];const patch={'system.combat.aura.value':aura+old-amount,['flags.'+NS+'.auraReservations119']:after};await actor.update(patch);try{const saved=item?await item.update(data,{gahlaAura119:true,gahlaPreparation:true}):(await actor.createEmbeddedDocuments('Item',[{...data,_id:id}],{keepId:true,gahlaAura119:true}))[0];if(!saved)throw Error('Zapis Manewru został anulowany.');return saved;}catch(error){await actor.update({'system.combat.aura.value':aura,['flags.'+NS+'.auraReservations119']:before});throw error;}});}
export async function releaseAura119(actor,id){return serial(actor.uuid,async()=>{const held=structuredClone(actor.flags?.[NS]?.auraReservations119??{}),amount=Number(held[id]||0);if(!amount)return;delete held[id];await actor.update({['flags.'+NS+'.auraReservations119']:held,'system.combat.aura.value':Number(actor.system.combat.aura.value)+amount});});}
export function registerAura119(){Hooks.on('deleteItem',(item,_options,userId)=>{if(item.parent&&userId===game.user.id)void releaseAura119(item.parent,item.id).catch(e=>ui.notifications.error(e.message));});Hooks.on('preCreateItem',(item,_data,options)=>{if(item.type==='maneuver'&&item.parent&&auraPayment119(item.system)>0&&!options?.gahlaAura119){ui.notifications.warn('Manewr opłacany Aurą utwórz Kreatorem, aby zablokować zasób.');return false;}});Hooks.on('preUpdateItem',(item,changes,options)=>{if(item.type!=='maneuver'||!item.parent||options?.gahlaAura119)return;const state=changes['system.builderState']??changes.system?.builderState;if(state!==undefined&&auraPayment119({builderState:state})!==auraPayment119(item.system)){ui.notifications.warn('Zmień płatność Aurą przez Kreator Manewrów.');return false;}});}
